### ISSUE TITLE
Configuration persistence never cleaned

### ISSUE THREAD

**Issue by fipro78** [apache/felix-atomos#54]
Hi,

while investigating on the behavior of different OSGi runtimes I noticed that the persistence is never cleared when using Atomos.

Attached are two simple setups that use Atomos. The application is basically a Gogo Shell with some commands that use SCR, ConfigAdmin and EventAdmin to verify if things are working.

For Felix the system property `-Dorg.osgi.framework.storage.clean=onFirstInit` should clean the persistence on start.
For Equinox I assumed `-clean` should do the same.

In both cases the persistence is never cleared. You can check this by starting the application and then call `fipro:configure <some_value>`. Then call `fipro:welcome` which actually reads the configuration value and prints it to the console. Then stop the application and start it again. With the mentioned clean parameters the `welcome` command should print `null`, but it always prints the previously configure value. So the configuration persistence area is never cleared.

[folder_atomos_equinox.zip](https://github.com/apache/felix-atomos/files/8670572/folder_atomos_equinox.zip)
[folder_atomos_felix.zip](https://github.com/apache/felix-atomos/files/8670575/folder_atomos_felix.zip)
.

**Comment by karlpauls** [comment]
At least for Felix, I don't think ```org.osgi.framework.storage.clean``` works as a system property. It will work if used as a framework property. 

In other words, for Felix, I think you need to pass it as an argument to the Atomos launcher - i.e., something like:

```
java -cp "bundles/*" org.apache.felix.atomos.Atomos org.osgi.framework.storage.clean=onFirstInit
```

**Comment by fipro78** [comment]
Everyday I learn a new detail. Thanks for the explanation. I will verify tomorrow and give a feedback here.

Btw, the system property works with the Felix launcher. Probably that is why I thought it should also work with atomos this way.

**Comment by karlpauls** [comment]
@fipro78, right - that is done by the Felix main [0]. The framework is only using the framework properties.  

[0] https://github.com/apache/felix-dev/blob/2bacc598b1cd00e84c69c54a3c77a03288204c6c/main/src/main/java/org/apache/felix/main/Main.java#L568

**Comment by fipro78** [comment]
Hi,

just in case someone is coming across this issue in the future, I can confirm that:

- With Atomos `org.osgi.framework.storage.clean=onFirstInit` needs to be passed as argument to the Atomos launcher as described by @karlpauls 
- Using the Equinox Framework directly (start via -jar org.eclipse.osgi) it can be passed as system property or you can use -`clean`
- Using the Felix Framework with the Felix Launcher (org.apache.felix.main) `org.osgi.framework.storage.clean=onFirstInit` can be set as system property

Thanks @tjwatson and @karlpauls  for the explanation.
