### ISSUE TITLE
Build error due to missing signature:java111

### ISSUE THREAD

**Issue by wolfgangimig** [apache/felix-atomos#56]
Build [commands](https://github.com/apache/felix-atomos#build) fail in my env.

Message:
`[ERROR] Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.18:check (default) on project atomos-parent: Failed to obtain signature: org.codehaus.mojo.signature:java111:1.0: Failure to find org.codehaus.mojo.signature:java111:signature:1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will...`

```
...:~/git/felix-atomos$ java -version
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)
```

```
...:~/git/felix-atomos$ mvn -version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 1.8.0_312, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.13.0-40-generic", arch: "amd64", family: "unix"
```

Thanks in advance for suggestions.

**Comment by rotty3000** [comment]
You may have java version 11 but clearly mvn used java 8 which is the issue.

Mvn will prefer to use java found from $JAVA_HOME. that's probably your
issue. Make sure it also points to java 11.

**Comment by wolfgangimig** [comment]
Maven takes the Java JAVA_HOME variable from ~/.mavenrc and ignores the environment variable.
After entering
`export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64`
in this config file the project compiles successfully. 
Thanks rotty3000
