### ISSUE TITLE
ClassCastException when retrieving a SaxParserFactory service ref created by Equinox from a "Standard Bundle"

### ISSUE THREAD

**Issue by sten-navie** [apache/felix-atomos#60]
During my experiments with Atomos I encountered the following issue.

Having the following modules in a bootlayer:

```
org.eclipse.osgi-3.17.200.jar
org.apache.felix.atomos-1.0.0.jar	
org.apache.felix.gogo.command-1.1.0.jar	
org.apache.felix.gogo.runtime-1.1.2.jar	
osgi.core-8.0.0-AtomosEquinox.jar
org.osgi.service.metatype-1.4.1.jar
org.osgi.service.cm-1.6.1.jar
```

First I start the above modules by placing them into a folder named atomos-test and running:
`java --add-modules=ALL-MODULE-PATH -p atomos-test -m org.apache.felix.atomos`

If I now try to install and start equinox.metatype as a "Standard Bundle" via the gogo-shell, I get a ClassCastException:

```
g! felix:install file:////PATH_TO_MY_FILES/org.eclipse.equinox.metatype-1.6.100.jar 
Bundle ID: 42

g! start 42
java.lang.ClassCastException: class com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl cannot be cast to class javax.xml.parsers.SAXParserFactory (com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl is in module java.xml of loader 'bootstrap'; javax.xml.parsers.SAXParserFactory is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @162a66a1)
```

- Tested with java 11 and 17.
- If I place the equinox.metatype jar into the atomos-test folder and run it from the boot-layer, everything works.

**Comment by tjwatson** [comment]
> javax.xml.parsers.SAXParserFactory is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @162a66a1)

This indicates to me that you may have another "normal" bundle that is exporting `javax.xml.parsers` package also?

**Comment by laeubi** [comment]
Do you use any startup options? Can you make sure that `osgi.compatibility.bootdelegation=false` is used?

**Comment by sten-navie** [comment]
> Do you use any startup options? Can you make sure that `osgi.compatibility.bootdelegation=false` is used?

For my simple test I do not set any startup options. So it is whatever options Atomos.main sets. 

I tried to add `osgi.compatibility.bootdelegation=false` but it does not change the result.

**Comment by tjwatson** [comment]
This is happening because `java.lang.Module.getClassLoader()` is returning null even though the javadoc says nothing about returning null.  It appears to return null for modules in the boot layer.  I guess that makes sense, but it means we need to handle the case for delegating to the boot layer modules for non java.* packages.

**Comment by sten-navie** [comment]
I can confirm that applying PR  #61 fixes this problem for me. Many thanks!

**Comment by tjwatson** [comment]
I went ahead and merged and opened an issue to add a testcase.
